[package]
name = "Rust-Whatweb"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.8", features = ["blocking"] }
tokio = { version = "1.41.0", features = ["rt", "rt-multi-thread", "macros"] }
clap = { version = "4.5.20", features = ["derive"] }
colored = "2.1.0"
